#docker-compose -f docker/dev/docker-compose.yml up --build
version: '2.0'

services:
  db_mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - data_db:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - internalnet
  back_end_moniciones_liturgicas:
    container_name: apiNode
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
    ports:
      - 3001:3001
    expose:
      - 3001
    environment:
      - DB_HOST=db_mysql
    depends_on: 
      - db_mysql
    networks:
      - internalnet
volumes:
  data_db:   

networks:
  internalnet:
    driver: bridge
